package ComplexApp;


/**
* ComplexApp/_ComplexIntStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ComplexIdl.idl
* Wednesday, November 23, 2016 2:51:17 PM WET
*/

public class _ComplexIntStub extends org.omg.CORBA.portable.ObjectImpl implements ComplexApp.ComplexInt
{

  public ComplexApp.Complex AddComplex (ComplexApp.Complex a, ComplexApp.Complex b)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("AddComplex", true);
                ComplexApp.ComplexHelper.write ($out, a);
                ComplexApp.ComplexHelper.write ($out, b);
                $in = _invoke ($out);
                ComplexApp.Complex $result = ComplexApp.ComplexHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return AddComplex (a, b        );
            } finally {
                _releaseReply ($in);
            }
  } // AddComplex

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ComplexApp/ComplexInt:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _ComplexIntStub
