package ComplexApp;


/**
* ComplexApp/ComplexIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ComplexIdl.idl
* Wednesday, November 23, 2016 2:51:17 PM WET
*/

public interface ComplexIntOperations 
{
  ComplexApp.Complex AddComplex (ComplexApp.Complex a, ComplexApp.Complex b);
} // interface ComplexIntOperations
