package ComplexApp;

/**
* ComplexApp/ComplexHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ComplexIdl.idl
* Wednesday, November 23, 2016 2:51:17 PM WET
*/

public final class ComplexHolder implements org.omg.CORBA.portable.Streamable
{
  public ComplexApp.Complex value = null;

  public ComplexHolder ()
  {
  }

  public ComplexHolder (ComplexApp.Complex initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ComplexApp.ComplexHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ComplexApp.ComplexHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ComplexApp.ComplexHelper.type ();
  }

}
