package Banque;


/**
* Banque/CompteInt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banque.idl
* Thursday, November 24, 2016 10:26:35 AM WET
*/

public interface CompteInt extends CompteIntOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CompteInt
