package Banque;


/**
* Banque/CompteIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banque.idl
* Thursday, November 24, 2016 10:26:35 AM WET
*/

public interface CompteIntOperations 
{
  void retirer (float mt);
  void verser (float mt);
  float getSolde ();
  int getCode ();
} // interface CompteIntOperations
