package ComplexApp;

/**
* ComplexApp/ComplexIntHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ComplexIdl.idl
* Wednesday, November 23, 2016 2:30:27 PM WET
*/

public final class ComplexIntHolder implements org.omg.CORBA.portable.Streamable
{
  public ComplexApp.ComplexInt value = null;

  public ComplexIntHolder ()
  {
  }

  public ComplexIntHolder (ComplexApp.ComplexInt initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ComplexApp.ComplexIntHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ComplexApp.ComplexIntHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ComplexApp.ComplexIntHelper.type ();
  }

}
