package Banque;


/**
* Banque/CompteIntPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banque.idl
* Thursday, November 24, 2016 10:26:35 AM WET
*/

public abstract class CompteIntPOA extends org.omg.PortableServer.Servant
 implements Banque.CompteIntOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("retirer", new java.lang.Integer (0));
    _methods.put ("verser", new java.lang.Integer (1));
    _methods.put ("getSolde", new java.lang.Integer (2));
    _methods.put ("getCode", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Banque/CompteInt/retirer
       {
         float mt = in.read_float ();
         this.retirer (mt);
         out = $rh.createReply();
         break;
       }

       case 1:  // Banque/CompteInt/verser
       {
         float mt = in.read_float ();
         this.verser (mt);
         out = $rh.createReply();
         break;
       }

       case 2:  // Banque/CompteInt/getSolde
       {
         float $result = (float)0;
         $result = this.getSolde ();
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 3:  // Banque/CompteInt/getCode
       {
         int $result = (int)0;
         $result = this.getCode ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Banque/CompteInt:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public CompteInt _this() 
  {
    return CompteIntHelper.narrow(
    super._this_object());
  }

  public CompteInt _this(org.omg.CORBA.ORB orb) 
  {
    return CompteIntHelper.narrow(
    super._this_object(orb));
  }


} // class CompteIntPOA
