package Banque;

/**
* Banque/CompteIntHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banque.idl
* Thursday, November 24, 2016 10:26:35 AM WET
*/

public final class CompteIntHolder implements org.omg.CORBA.portable.Streamable
{
  public Banque.CompteInt value = null;

  public CompteIntHolder ()
  {
  }

  public CompteIntHolder (Banque.CompteInt initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Banque.CompteIntHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Banque.CompteIntHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Banque.CompteIntHelper.type ();
  }

}
