package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Wednesday, November 23, 2016 1:35:44 PM WET
*/

public interface HelloOperations 
{
  String SayHello ();
} // interface HelloOperations
