package ComplexApp;


/**
* ComplexApp/ComplexIntPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ComplexIdl.idl
* Wednesday, November 23, 2016 2:51:17 PM WET
*/

public abstract class ComplexIntPOA extends org.omg.PortableServer.Servant
 implements ComplexApp.ComplexIntOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("AddComplex", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ComplexApp/ComplexInt/AddComplex
       {
         ComplexApp.Complex a = ComplexApp.ComplexHelper.read (in);
         ComplexApp.Complex b = ComplexApp.ComplexHelper.read (in);
         ComplexApp.Complex $result = null;
         $result = this.AddComplex (a, b);
         out = $rh.createReply();
         ComplexApp.ComplexHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ComplexApp/ComplexInt:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ComplexInt _this() 
  {
    return ComplexIntHelper.narrow(
    super._this_object());
  }

  public ComplexInt _this(org.omg.CORBA.ORB orb) 
  {
    return ComplexIntHelper.narrow(
    super._this_object(orb));
  }


} // class ComplexIntPOA
