package Bank;


/**
* Bank/Transaction.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bank.idl
* Thursday, November 24, 2016 11:42:16 AM WET
*/

public interface Transaction extends TransactionOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Transaction
