package Bank;


/**
* Bank/TransactionPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bank.idl
* Thursday, November 24, 2016 11:42:16 AM WET
*/

public abstract class TransactionPOA extends org.omg.PortableServer.Servant
 implements Bank.TransactionOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("updateDetails", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Bank/Transaction/updateDetails
       {
         String counterId = in.read_string ();
         String date = in.read_string ();
         double amountDebit = in.read_double ();
         double amountCredit = in.read_double ();
         String accountId = in.read_string ();
         String $result = null;
         $result = this.updateDetails (counterId, date, amountDebit, amountCredit, accountId);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Bank/Transaction:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Transaction _this() 
  {
    return TransactionHelper.narrow(
    super._this_object());
  }

  public Transaction _this(org.omg.CORBA.ORB orb) 
  {
    return TransactionHelper.narrow(
    super._this_object(orb));
  }


} // class TransactionPOA
