package Bank;


/**
* Bank/TransactionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bank.idl
* Thursday, November 24, 2016 11:42:16 AM WET
*/

public interface TransactionOperations 
{
  String updateDetails (String counterId, String date, double amountDebit, double amountCredit, String accountId);
} // interface TransactionOperations
