package ComplexApp;


/**
* ComplexApp/ComplexIntHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ComplexIdl.idl
* Wednesday, November 23, 2016 2:30:27 PM WET
*/

abstract public class ComplexIntHelper
{
  private static String  _id = "IDL:ComplexApp/ComplexInt:1.0";

  public static void insert (org.omg.CORBA.Any a, ComplexApp.ComplexInt that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ComplexApp.ComplexInt extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ComplexApp.ComplexIntHelper.id (), "ComplexInt");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ComplexApp.ComplexInt read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ComplexIntStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ComplexApp.ComplexInt value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ComplexApp.ComplexInt narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ComplexApp.ComplexInt)
      return (ComplexApp.ComplexInt)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ComplexApp._ComplexIntStub stub = new ComplexApp._ComplexIntStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ComplexApp.ComplexInt unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ComplexApp.ComplexInt)
      return (ComplexApp.ComplexInt)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ComplexApp._ComplexIntStub stub = new ComplexApp._ComplexIntStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
