package ComplexApp;


/**
* ComplexApp/ComplexHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ComplexIdl.idl
* Wednesday, November 23, 2016 2:30:27 PM WET
*/

abstract public class ComplexHelper
{
  private static String  _id = "IDL:ComplexApp/Complex:1.0";

  public static void insert (org.omg.CORBA.Any a, ComplexApp.Complex that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ComplexApp.Complex extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_double);
          _members0[0] = new org.omg.CORBA.StructMember (
            "re",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_double);
          _members0[1] = new org.omg.CORBA.StructMember (
            "im",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (ComplexApp.ComplexHelper.id (), "Complex", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ComplexApp.Complex read (org.omg.CORBA.portable.InputStream istream)
  {
    ComplexApp.Complex value = new ComplexApp.Complex ();
    value.re = istream.read_double ();
    value.im = istream.read_double ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ComplexApp.Complex value)
  {
    ostream.write_double (value.re);
    ostream.write_double (value.im);
  }

}
