package Bank;


/**
* Bank/_TransactionStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bank.idl
* Sunday, January 8, 2017 12:30:34 PM CET
*/

public class _TransactionStub extends org.omg.CORBA.portable.ObjectImpl implements Bank.Transaction
{

  public String updateDetails (String counterId, String date, double amountDebit, double amountCredit, String accountId)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("updateDetails", true);
                $out.write_string (counterId);
                $out.write_string (date);
                $out.write_double (amountDebit);
                $out.write_double (amountCredit);
                $out.write_string (accountId);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return updateDetails (counterId, date, amountDebit, amountCredit, accountId        );
            } finally {
                _releaseReply ($in);
            }
  } // updateDetails

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Bank/Transaction:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _TransactionStub
