package Bank;


/**
* Bank/Transaction.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bank.idl
* Sunday, January 8, 2017 12:30:34 PM CET
*/

public interface Transaction extends TransactionOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Transaction
