package Bank;


/**
* Bank/TransactionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bank.idl
* Sunday, January 8, 2017 12:30:34 PM CET
*/

public interface TransactionOperations 
{
  String updateDetails (String counterId, String date, double amountDebit, double amountCredit, String accountId);
} // interface TransactionOperations
